# Generated by Django 5.1.2 on 2024-10-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('reservation_slot', models.TimeField()),
            ],
        ),
    ]
